### ISSUE TITLE
Switch to crc-32 for faster hashing of files

### ISSUE THREAD

**Issue by wckd** [eigan/mediasort#2]
Consider switching to CRC-32 for faster hashing of files, and if collision/equal - do a re-run with sha1 or md5.

https://stackoverflow.com/a/1761615

**Comment by eigan** [comment]
I think we will most likely have to verify with sha1/md5 anyway.

In my tests would it only use hash checking when I did a rerun with --link, __meaning that the same file would like to be linked at the same place.__ And in this case would both crc-32 and md5 need to be checked. 

Comparing files (with  hash) is currently the biggest bottleneck, so I am really interested in ways to optimize this. 

Will do some testing with crc-32. Thanks!

**Comment by eigan** [comment]
Doesnt look like there is much benefit for checking with crc-32 before md5. Checking filesize first (which we do) is a lot faster. 

Closing because #3 fixes the biggest issue I had with speed.
